# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  flutter_test:
    name: Run flutter test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
    - run: flutter pub get
    - run: flutter test --no-sound-null-safety --coverage

  build:
    name: Build Flutter App (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@master
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk    
    
    
  build_ios:
    name: Build Flutter App (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
        
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
    - run: flutter pub get
    - run: flutter clean
    - run: flutter build ios --no-codesign
  
     # Upload generated IPA to the artifacts.
    - uses: actions/upload-artifact@master
      with:
        name: ios-build
        path: build/ios/iphoneos   
    
